In [20]:
import pandas as pd
import numpy as np

In [21]:
class BasicAnn:
    def __init__(self, layers):
        weight_shapes = [(layers[i],layers[i-1]) for i in range(1, len(layers))]
        self.weights = [np.random.standard_normal(s)/s[1]**0.5 for s in weight_shapes]
        self.biases = [np.random.randn(y,1) for y in layers[1:]]
    

In [22]:
BasicAnn((2,5,3,2))

[[ 0.14752363 -0.06110104]
 [-0.62238783 -0.60189095]
 [ 0.52993836  0.25658304]
 [ 0.00645277 -1.84870428]
 [ 0.67683989 -0.15363934]]
[[ 0.1797233  -0.04561444 -0.12239586 -0.06895181 -0.29708243]
 [-0.20887302  0.55651611 -0.06224417 -0.19536555 -0.50836433]
 [-0.13157998  0.21901513  0.2141659  -0.01253509 -0.2827316 ]]
[[-1.08735507  0.26712946 -0.94929899]
 [-0.1429541   0.09097664  0.12948194]]
[[ 1.31500132]
 [-0.01769685]
 [-0.92777253]
 [ 1.31288101]
 [-0.18551263]]
[[-0.96500454]
 [-1.65331586]
 [ 1.21065786]]
[[-0.73292982]
 [-1.1580277 ]]


NameError: name 'sqrt' is not defined