In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.random.randn(3,4)
b = np.random.randn(1,4)
c = a + b

In [3]:
c

array([[ 0.68431032, -0.90778851,  0.93301996, -0.47148466],
       [ 0.78689989,  2.75906674,  0.1912874 , -1.32480048],
       [ 0.84848619, -2.20779653,  1.12998424, -0.33293467]])

In [4]:
a = np.random.randn(1,3) 
b = np.random.randn(3,3)
c = a*b

In [5]:
c

array([[-0.50381247, -0.06931424,  2.7924775 ],
       [-0.05058894, -0.10198521,  1.06553755],
       [ 0.20327426, -0.40919466, -1.31072933]])

In [6]:
a=np.random.randn(12288,150) 

# a.shape = (12288, 150)a.shape=(12288,150)

b = np.random.randn(150, 45)

# b.shape = (150, 45)b.shape=(150,45)

c = np.dot(a,b)
c.shape

(12288, 45)

In [7]:
img = np.random.randn(32,32,3)
img.reshape((32*32*3,1))

array([[-0.38796114],
       [-0.97664617],
       [-2.20665468],
       ...,
       [ 0.0799612 ],
       [-1.37700337],
       [ 0.31183263]])

In [8]:
arr_1 = np.random.randn(3, 3)
arr_1 < 0.5

array([[ True,  True, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
c.shape

(0,)

In [10]:
x = np.random.rand(4, 5)

y = np.sum(x, axis=1)
y.shape

(4,)