In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.random.randn(3,4)
b = np.random.randn(1,4)
c = a + b

In [3]:
c

array([[ 1.71660054, -1.23652683,  0.71177714, -0.47852737],
       [ 1.6732751 ,  2.14430189, -0.70409514,  2.36772099],
       [-0.73251587,  0.58623299, -2.60212476,  1.09757667]])

In [4]:
a = np.random.randn(1,3) 
b = np.random.randn(3,3)
c = a*b

In [5]:
c

array([[-0.0393399 , -0.17653146,  1.3577612 ],
       [ 0.01144543, -0.07052044,  0.65314703],
       [-0.24793355, -0.74128178,  1.64384583]])

In [6]:
a=np.random.randn(12288,150) 

# a.shape = (12288, 150)a.shape=(12288,150)

b = np.random.randn(150, 45)

# b.shape = (150, 45)b.shape=(150,45)

c = np.dot(a,b)
c.shape

(12288, 45)

In [7]:
img = np.random.randn(32,32,3)
img.reshape((32*32*3,1))

array([[ 0.62828549],
       [-1.08057475],
       [ 1.24241342],
       ...,
       [-0.15592413],
       [ 0.11621306],
       [ 0.65889786]])

In [8]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)
c = np.array([])

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [9]:
c.shape

(0,)

In [10]:
A = np.random.randn(4,3)

B = np.sum(A, axis = 1, keepdims = True)
B.shape

(4, 1)