In [1]:
import numpy as np
import pandas as pd

In [4]:
a = np.random.randn(5,4)
b = np.random.randn(1,4)
c = a + b

In [5]:
c

array([[-2.50204725, -0.53457149,  1.41001849,  0.68731757],
       [-0.14077583,  0.91471122,  1.80621588,  1.29974701],
       [-0.16560697, -0.01714736,  2.30868093,  1.25905113],
       [-1.07810657, -1.78845309,  0.41841908,  0.67615725],
       [-1.61893216, -1.82666841,  1.32369931,  2.42896054]])

In [6]:
a = np.random.randn(1,3)
b = np.random.randn(3,3)
c = a*b

In [7]:
c

array([[-0.14973838,  0.11500825, -1.39339704],
       [ 2.62649618, -0.25880284, -2.1377661 ],
       [ 0.31553991, -0.01853859, -1.02908061]])

In [8]:
a=np.random.randn(12288,150)

# a.shape = (12288, 150)a.shape=(12288,150)

b = np.random.randn(150, 45)

# b.shape = (150, 45)b.shape=(150,45)

c = np.dot(a,b)
c.shape

(12288, 45)

In [9]:
img = np.random.randn(32,32,3)
img.reshape((32*32*3,1))

array([[ 1.35325938],
       [ 1.32764641],
       [-1.52496565],
       ...,
       [-1.25474791],
       [-0.69881507],
       [-1.06119012]])

In [10]:
arr_1 = np.random.randn(3, 3)
arr_1 < 0.5

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
c.shape

(12288, 45)

In [12]:
x = np.random.rand(4, 5)

y = np.sum(x, axis=1)
y.shape

(4,)

In [13]:
import numpy as np
import plotly.graph_objects as go
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import GridSearchCV, cross_val_score, KFold

# Assume we have some 2D data array X and target array y
# For example, using the Boston dataset:
boston = datasets.load_iris()
X = boston.data
y = boston.target
print(f"X = {X.shape}")

# Define the parameter values that should be searched for SVR model
parameter_candidates = [
  {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
  {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},
]

# Create a classifier object with the classifier and parameter candidates
clf = GridSearchCV(estimator=svm.SVR(), param_grid=parameter_candidates, cv=5)

# Calculate R^2 score using nested cross-validation
# 2nd CV: clf (GridSearchCV) is performing the inner cross-validation for hyperparameter tuning
# 1st CV: KFold is performing the outer cross-validation for model evaluation
kf = KFold(n_splits=5)

fold = []
score = []
for i, (train_index, test_index) in enumerate(kf.split(X)):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    clf.fit(X_train, y_train)
    fold.append(f'Fold {i+1}')
    score.append(clf.score(X_test, y_test))

# Define the figure
fig = go.Figure(data=[go.Bar(x=fold, y=score)])

# Add title and labels
fig.update_layout(title_text='R^2 scores for each fold in nested cross validation',
                  xaxis_title='Fold',
                  yaxis_title='R^2 score')

# Show the plot
fig.show()

X = (150, 4)


In [14]:
import numpy as np
from sklearn import datasets
from sklearn.metrics import precision_recall_curve, roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
import plotly.graph_objects as go

# Load iris dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Binarize the output
y = label_binarize(y, classes=[0, 1, 2])
n_classes = y.shape[1]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train SVC model
classifier = OneVsRestClassifier(SVC(kernel='linear', probability=True))
y_score = classifier.fit(X_train, y_train).decision_function(X_test)

# Compute Precision-Recall and ROC curves
precision = dict()
recall = dict()
average_precision = dict()
fpr = dict()
tpr = dict()
roc_auc = dict()

for i in range(n_classes):
    precision[i], recall[i], _ = precision_recall_curve(y_test[:, i], y_score[:, i])
    average_precision[i] = auc(recall[i], precision[i])

    fpr[i], tpr[i], _ = roc_curve(y_test[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Plot ROC and Precision-Recall curves using plotly
for i in range(n_classes):
    trace0 = go.Scatter(x=recall[i], y=precision[i], mode='lines', name='Precision-Recall curve of class {0} (area = {1:0.2f})'.format(i, average_precision[i]))
    trace1 = go.Scatter(x=fpr[i], y=tpr[i], mode='lines', name='ROC curve of class {0} (area = {1:0.2f})'.format(i, roc_auc[i]))

    fig = go.Figure(data=[trace0, trace1])
    fig.update_layout(title='Precision-Recall and ROC curves',
                   xaxis_title='Recall / False Positive Rate',
                   yaxis_title='Precision / True Positive Rate')

    fig.show()


In [15]:
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split
import plotly.graph_objects as go
import plotly.subplots as sp

# Create some sample data
np.random.seed(0)
X = np.sort(5 * np.random.rand(40, 1), axis=0)
y = np.sin(X).ravel()
y[::5] += 3 * (0.5 - np.random.rand(8))

# Split the data into training/testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the SVR model
svr = svm.SVR(kernel='rbf', C=100, gamma=0.1, epsilon=.1)
svr.fit(X_train, y_train)

# Make predictions using the testing set
y_pred = svr.predict(X_test)

# Plotting

# 1. Data Scatter Plot and 2. Regression Line Plot
fig1 = go.Figure()
fig1.add_trace(go.Scatter(x=X_train.ravel(), y=y_train, mode='markers', name='Data'))
fig1.add_trace(go.Scatter(x=X_test.ravel(), y=y_pred, mode='lines', name='SVR Fit'))
fig1.update_layout(title='Data Scatter Plot and Regression Line Plot',
                   xaxis_title='X',
                   yaxis_title='y')

# 3. Residuals Plot
residuals = y_test - y_pred
fig2 = go.Figure()
fig2.add_trace(go.Scatter(x=y_pred, y=residuals, mode='markers'))
fig2.update_layout(title='Residuals Plot',
                   xaxis_title='Predicted Values',
                   yaxis_title='Residuals')

# 4. Prediction Error Plot
fig3 = go.Figure()
fig3.add_trace(go.Scatter(x=y_test, y=y_pred, mode='markers'))
fig3.add_trace(go.Scatter(x=[min(y_test), max(y_test)], y=[min(y_test), max(y_test)], mode='lines', name='Ideal Fit'))
fig3.update_layout(title='Prediction Error Plot',
                   xaxis_title='True Values',
                   yaxis_title='Predicted Values')

fig1.show()
fig2.show()
fig3.show()


In [16]:
np.arange(0,1, 0.01)

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

In [17]:
round(0.467, 2)

0.47

In [18]:
import numpy as np
from sklearn import datasets
from sklearn import svm
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
from scipy import stats

# load dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target

# define models
model1 = svm.SVC()
model2 = MLPClassifier(random_state=1, max_iter=300)

# perform 10-fold cross validation
scores1 = cross_val_score(model1, X, y, cv=10)
scores2 = cross_val_score(model2, X, y, cv=10)

# use paired t-test to see if difference in mean scores is significant
t_stat, p_val = stats.ttest_rel(scores1, scores2)

print(f'T-statistic: {t_stat}')
print(f'p-value: {p_val}')

import plotly.graph_objects as go

# Calculate differences
differences = scores1 - scores2

# Box plot for scores
fig = go.Figure()
fig.add_trace(go.Box(y=scores1, name='SVC'))
fig.add_trace(go.Box(y=scores2, name='MLPClassifier'))
fig.update_layout(title='Box Plot of Model Scores', yaxis_title='Scores')
fig.show()

# Histogram of differences
fig = go.Figure(data=[go.Histogram(x=differences)])
fig.update_layout(title='Histogram of Differences in Scores', xaxis_title='Differences')
fig.show()

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning:

Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning:

Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning:

Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning:

Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning:

Stochastic Optimizer: Maximum

T-statistic: -0.36115755925730764
p-value: 0.7263142108887259


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning:

Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.



In [19]:
# Box plot for scores
fig = go.Figure()
fig.add_trace(go.Box(y=scores1, name='SVC'))
fig.add_trace(go.Box(y=scores2, name='MLPClassifier'))
fig.update_layout(title='Box Plot of Model Scores', yaxis_title='Scores')
fig.show()

In [20]:
np.append(np.array([4,5,6]), [7,8,9])

array([4, 5, 6, 7, 8, 9])

In [21]:
list(np.array([1,2,3])) + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [22]:
np.array([1,2,3]).size

3

In [23]:
from sklearn.metrics import get_scorer_names
get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',