In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.random.randn(3,4)
b = np.random.randn(1,4)
c = a + b

In [4]:
c

array([[-1.77050372,  1.75767193, -0.96325987, -1.05309166],
       [-3.32710425,  0.66774057,  0.20266402,  0.78316054],
       [-1.96351276,  1.5987882 , -1.40445756, -1.46125392]])

In [5]:
a = np.random.randn(1,3) 
b = np.random.randn(3,3)
c = a*b

In [6]:
c

array([[ 0.00102357,  0.13198032, -0.06789391],
       [ 0.04197219, -0.05505058,  0.29125421],
       [ 0.03962854,  0.56624625, -0.35226805]])

In [7]:
a=np.random.randn(12288,150) 

# a.shape = (12288, 150)a.shape=(12288,150)

b = np.random.randn(150, 45)

# b.shape = (150, 45)b.shape=(150,45)

c = np.dot(a,b)
c.shape

(12288, 45)

In [16]:
img = np.random.randn(32,32,3)
img.reshape((32*32*3,1))

array([[-1.45567132],
       [-0.1214584 ],
       [-0.73687945],
       ...,
       [-0.37225296],
       [-0.49811206],
       [-0.08592427]])

In [15]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)
c = np.array([])

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [14]:
c.shape

(12288, 45)