# Imports

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# DeepLearning.AI — MLS C1 Labs

## W1-Lab02
As in the lecture, you will use the motivating example of housing price prediction.
This lab will use a simple data set with only two data points - a house with 1000 square feet(sqft)
sold for \\$300k  and a house with 2000 square feet sold for $500k.
 
These two points will
constitute our data or training set. In this lab, the units of size are 1000 sqft and the units of price are 1000s of dollars.

In [2]:
# Training data
x_train = np.array([1.2, 3.4, 5.6, 7.8, 9.0])
y_train = np.array([210.3, 430.5, 650.7, 870.9, 900.1])

In [3]:
# Number of training examples
m = x_train.shape[0]
m

5

#### Plotting

In [96]:
# Plotting
def plot_data(x, y):
    plot = px.scatter(
        x=x, 
        y=y, 
        title="Housing Prices", 
        labels={'x': 'Square Footage (1000 sqft)', 'y': 'Price (in 1000s of dollars)'}
    )
    return plot

def plot_data_with_trendline(x, y, line, line_x):
    fig = go.Figure(layout={
        "title": "House Prices",
        "xaxis": {"title": "Square Footage (1000 sqft)"},
        "yaxis": {"title": "Price (in 1000s of dollars)"}
    })
    data = go.Scatter(x=x, y=y, mode='markers', name="Real Price Values")
    trendline = go.Scatter(x=line_x, y=line, mode='lines', name="Predicted Price Values")
    fig.add_trace(data)
    fig.add_trace(trendline)
    return fig

In [97]:
first_plot = plot_data(x_train, y_train)
first_plot.show()

#### Basic Model

In [98]:
def compute_model(x, w, b):
    return w * x + b

In [99]:
f_wb = compute_model(x_train, 99, 95)
plot_data_with_trendline(x_train, y_train, f_wb, x_train)

In [100]:
new_yardage = np.sort(np.array([12,34,5,6,2,5,3,1]))
new_prices = compute_model(new_yardage, 99, 95)

In [101]:
second_plot = plot_data(new_yardage, new_prices)

In [102]:
second_plot.show()

In [103]:
line = compute_model(np.arange(0,35), 99, 95)
third_plot = plot_data_with_trendline(
    new_yardage, 
    new_prices, 
    line,
    np.arange(0,35)
)
third_plot.show()

## W1-Lab03
Goals: In this lab you will: - you will implement and explore the cost function for linear regression withone variable. You would like a model which can predict housing prices given the size of the house.Let’s use the same two data points as before the previous lab.

In [132]:
def compute_cost(y, yhat, m):
    return (np.sum(yhat - y) ** 2) / (2 * m)

In [133]:
f_wb

array([213.8, 431.6, 649.4, 867.2, 986. ])

In [137]:
plot_data_with_trendline(x_train, y_train, f_wb, x_train)

In [139]:
compute_cost(y_train, f_wb, x_train.shape[0])

731.0249999999971

In [140]:
f_wb2 = compute_model(x_train, 50, -16)
f_wb2

array([ 44., 154., 264., 374., 434.])

In [143]:
plot_data_with_trendline(x_train, y_train, f_wb2, x_train)

In [145]:
compute_cost(y_train, f_wb2, x_train.shape[0])

321305.625

# Random Stuff

In [104]:
np.linspace(10, 100, 5)

array([ 10. ,  32.5,  55. ,  77.5, 100. ])

In [119]:
min_val = 0
max_val = 2 * np.pi
interval = 100

x = np.linspace(min_val, max_val, interval)
sin_x = np.sin(x)
cos_x = np.cos(x)

plot_data_with_trendline(x, sin_x, cos_x, x)