# Imports

In [2]:
import torch
import tensorflow as tf

2024-02-10 15:41:48.260619: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


## Data Manipulation

In [7]:
x_p = torch.arange(1, 13, dtype=torch.float32)
x_t = tf.range(1,13, dtype=tf.float32)

In [5]:
x_p

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [6]:
x_t

<tf.Tensor: shape=(11,), dtype=float32, numpy=
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.],
      dtype=float32)>

In [11]:
x_p ** x_t

<tf.Tensor: shape=(12,), dtype=float32, numpy=
array([1.0000000e+00, 4.0000000e+00, 2.7000000e+01, 2.5600000e+02,
       3.1250000e+03, 4.6656000e+04, 8.2354300e+05, 1.6777216e+07,
       3.8742048e+08, 1.0000000e+10, 2.8531166e+11, 8.9161004e+12],
      dtype=float32)>

In [12]:
x_p.numel()

12

In [17]:
tf.size(x_t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [19]:
x_t.shape

TensorShape([12])

In [20]:
z_p = x_p.reshape(3,4)
z_p

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [22]:
z_p[0, 3]

tensor(4.)

In [25]:
x_p.reshape(6, -1)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [26]:
x_p

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

### Zeros and Ones

In [28]:
y = torch.zeros(2,3,4)
y

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [35]:
y.reshape(6,2,-1)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [37]:
z = torch.ones(2,3,4)
z

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### Random Numbers

In [55]:
a = torch.rand(2,3,4) * 10
a

tensor([[[4.7817, 7.8731, 6.4300, 1.5912],
         [3.1955, 2.1673, 4.2195, 0.4662],
         [7.1313, 9.8152, 6.7317, 8.4975]],

        [[7.0272, 5.4637, 8.8992, 6.0284],
         [1.6086, 4.8453, 4.2232, 4.4114],
         [1.7687, 0.7766, 2.2216, 5.7903]]])

In [58]:
a.round()

tensor([[[ 5.,  8.,  6.,  2.],
         [ 3.,  2.,  4.,  0.],
         [ 7., 10.,  7.,  8.]],

        [[ 7.,  5.,  9.,  6.],
         [ 2.,  5.,  4.,  4.],
         [ 2.,  1.,  2.,  6.]]])

In [48]:
a[0,2,1] = 10101
a

tensor([[[ 1.0418e+01,  8.3034e+00,  6.2576e+00, -1.2419e+01],
         [ 1.3756e+00,  1.7472e+00,  1.8974e+01, -1.3611e+01],
         [ 1.8403e+01,  1.0101e+04,  5.3092e+00, -6.3796e+00]],

        [[ 4.5733e-01,  1.1958e+01, -2.7008e+00, -8.7040e+00],
         [ 1.5059e+00,  1.3973e+00,  8.8949e+00, -2.7479e+00],
         [-7.8090e+00, -4.3775e+00,  1.8147e+00,  2.1252e+01]]])

### Operations

In [90]:
x = torch.arange(1,21, dtype=torch.float32).reshape(5, -1)
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.]])

In [91]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05],
        [4.4241e+05, 1.2026e+06, 3.2690e+06, 8.8861e+06],
        [2.4155e+07, 6.5660e+07, 1.7848e+08, 4.8517e+08]])

In [92]:
y = (torch.rand(20) * 10).round().reshape(5,-1)
y

tensor([[8., 1., 1., 9.],
        [6., 8., 1., 4.],
        [4., 4., 4., 5.],
        [5., 9., 1., 6.],
        [6., 8., 2., 4.]])

In [93]:
x+y, x-y, x*y, x/y, y/x, x**y

(tensor([[ 9.,  3.,  4., 13.],
         [11., 14.,  8., 12.],
         [13., 14., 15., 17.],
         [18., 23., 16., 22.],
         [23., 26., 21., 24.]]),
 tensor([[-7.,  1.,  2., -5.],
         [-1., -2.,  6.,  4.],
         [ 5.,  6.,  7.,  7.],
         [ 8.,  5., 14., 10.],
         [11., 10., 17., 16.]]),
 tensor([[  8.,   2.,   3.,  36.],
         [ 30.,  48.,   7.,  32.],
         [ 36.,  40.,  44.,  60.],
         [ 65., 126.,  15.,  96.],
         [102., 144.,  38.,  80.]]),
 tensor([[ 0.1250,  2.0000,  3.0000,  0.4444],
         [ 0.8333,  0.7500,  7.0000,  2.0000],
         [ 2.2500,  2.5000,  2.7500,  2.4000],
         [ 2.6000,  1.5556, 15.0000,  2.6667],
         [ 2.8333,  2.2500,  9.5000,  5.0000]]),
 tensor([[8.0000, 0.5000, 0.3333, 2.2500],
         [1.2000, 1.3333, 0.1429, 0.5000],
         [0.4444, 0.4000, 0.3636, 0.4167],
         [0.3846, 0.6429, 0.0667, 0.3750],
         [0.3529, 0.4444, 0.1053, 0.2000]]),
 tensor([[1.0000e+00, 2.0000e+00, 3.0000e+00, 2.6214e+0

In [94]:
torch.cat((x,y), dim=0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [ 8.,  1.,  1.,  9.],
        [ 6.,  8.,  1.,  4.],
        [ 4.,  4.,  4.,  5.],
        [ 5.,  9.,  1.,  6.],
        [ 6.,  8.,  2.,  4.]])

In [95]:
torch.cat((x,y), dim=1)

tensor([[ 1.,  2.,  3.,  4.,  8.,  1.,  1.,  9.],
        [ 5.,  6.,  7.,  8.,  6.,  8.,  1.,  4.],
        [ 9., 10., 11., 12.,  4.,  4.,  4.,  5.],
        [13., 14., 15., 16.,  5.,  9.,  1.,  6.],
        [17., 18., 19., 20.,  6.,  8.,  2.,  4.]])

In [100]:
abs(x-y) <= 5

tensor([[False,  True,  True,  True],
        [ True,  True, False,  True],
        [ True, False, False, False],
        [False,  True, False, False],
        [False, False, False, False]])

In [101]:
x.sum(), y.sum()

(tensor(210.), tensor(96.))