# Imports

In [43]:
import torch
import tensorflow as tf
import numpy as np

## Data Manipulation

In [2]:
x_p = torch.arange(1, 13, dtype=torch.float32)
x_p

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [3]:
x_p.numel()

12

In [4]:
tf.size(x_p)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [6]:
z_p = x_p.reshape(3,4)
z_p

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [7]:
z_p[0, 3]

tensor(4.)

In [8]:
x_p.reshape(6, -1)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [9]:
x_p

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

### Zeros and Ones

In [10]:
y = torch.zeros(2,3,4)
y

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
y.reshape(6,2,-1)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [12]:
z = torch.ones(2,3,4)
z

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

### Random Numbers

In [13]:
a = torch.rand(2,3,4) * 10
a

tensor([[[4.7216, 9.9772, 0.9173, 7.9551],
         [7.1746, 1.5884, 9.5906, 3.1432],
         [1.3604, 4.9939, 9.5583, 4.7661]],

        [[2.4870, 3.9943, 2.1535, 7.9310],
         [7.6543, 0.9194, 5.7744, 4.5147],
         [7.2574, 8.4284, 7.3981, 2.8357]]])

In [14]:
a.round()

tensor([[[ 5., 10.,  1.,  8.],
         [ 7.,  2., 10.,  3.],
         [ 1.,  5., 10.,  5.]],

        [[ 2.,  4.,  2.,  8.],
         [ 8.,  1.,  6.,  5.],
         [ 7.,  8.,  7.,  3.]]])

### Operations

In [15]:
x = torch.arange(1,21, dtype=torch.float32).reshape(5, -1)
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.]])

In [16]:
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05],
        [4.4241e+05, 1.2026e+06, 3.2690e+06, 8.8861e+06],
        [2.4155e+07, 6.5660e+07, 1.7848e+08, 4.8517e+08]])

In [17]:
y = (torch.rand(20) * 10).round().reshape(5,-1)
y

tensor([[3., 7., 4., 2.],
        [9., 6., 7., 6.],
        [7., 3., 1., 1.],
        [9., 7., 5., 6.],
        [9., 4., 9., 1.]])

In [18]:
x+y, x-y, x*y, x/y, y/x, x**y

(tensor([[ 4.,  9.,  7.,  6.],
         [14., 12., 14., 14.],
         [16., 13., 12., 13.],
         [22., 21., 20., 22.],
         [26., 22., 28., 21.]]),
 tensor([[-2., -5., -1.,  2.],
         [-4.,  0.,  0.,  2.],
         [ 2.,  7., 10., 11.],
         [ 4.,  7., 10., 10.],
         [ 8., 14., 10., 19.]]),
 tensor([[  3.,  14.,  12.,   8.],
         [ 45.,  36.,  49.,  48.],
         [ 63.,  30.,  11.,  12.],
         [117.,  98.,  75.,  96.],
         [153.,  72., 171.,  20.]]),
 tensor([[ 0.3333,  0.2857,  0.7500,  2.0000],
         [ 0.5556,  1.0000,  1.0000,  1.3333],
         [ 1.2857,  3.3333, 11.0000, 12.0000],
         [ 1.4444,  2.0000,  3.0000,  2.6667],
         [ 1.8889,  4.5000,  2.1111, 20.0000]]),
 tensor([[3.0000, 3.5000, 1.3333, 0.5000],
         [1.8000, 1.0000, 1.0000, 0.7500],
         [0.7778, 0.3000, 0.0909, 0.0833],
         [0.6923, 0.5000, 0.3333, 0.3750],
         [0.5294, 0.2222, 0.4737, 0.0500]]),
 tensor([[1.0000e+00, 1.2800e+02, 8.1000e+01, 1.6000e+0

In [19]:
torch.cat((x,y), dim=0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [ 3.,  7.,  4.,  2.],
        [ 9.,  6.,  7.,  6.],
        [ 7.,  3.,  1.,  1.],
        [ 9.,  7.,  5.,  6.],
        [ 9.,  4.,  9.,  1.]])

In [20]:
torch.cat((x,y), dim=1)

tensor([[ 1.,  2.,  3.,  4.,  3.,  7.,  4.,  2.],
        [ 5.,  6.,  7.,  8.,  9.,  6.,  7.,  6.],
        [ 9., 10., 11., 12.,  7.,  3.,  1.,  1.],
        [13., 14., 15., 16.,  9.,  7.,  5.,  6.],
        [17., 18., 19., 20.,  9.,  4.,  9.,  1.]])

In [21]:
abs(x-y) <= 5

tensor([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True, False, False, False],
        [ True, False, False, False],
        [False, False, False, False]])

In [22]:
x.sum(), y.sum()

(tensor(210.), tensor(106.))

## Data Preprocessing

In [23]:
import os
import pandas as pd

In [24]:
os.makedirs(os.path.join('data'), exist_ok=True)
data_file = os.path.join('data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [25]:
data = pd.read_csv(data_file)
data

NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000

In [26]:
features, targets = data.iloc[:, 0:2], data.iloc[:, 2]
features, targets

(   NumRooms RoofType
 0       NaN      NaN
 1       2.0      NaN
 2       4.0    Slate
 3       NaN      NaN,
 0    127500
 1    106000
 2    178100
 3    140000
 Name: Price, dtype: int64)

In [27]:
features = pd.get_dummies(features, dummy_na=True)
features

NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True

In [28]:
features = features.fillna(features.mean())
features

NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True

In [29]:
X = torch.tensor(features.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

## Linear Algebra

In [30]:
equal = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
equal

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [31]:
equal.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [32]:
a = torch.rand(27).reshape(3,3,3)
a

tensor([[[0.4947, 0.2577, 0.0593],
         [0.0729, 0.2032, 0.6913],
         [0.7213, 0.5609, 0.4829]],

        [[0.0767, 0.3047, 0.9098],
         [0.4706, 0.5555, 0.0136],
         [0.5978, 0.9008, 0.0293]],

        [[0.3362, 0.5042, 0.1604],
         [0.8592, 0.1586, 0.6206],
         [0.1451, 0.4788, 0.4833]]])

In [33]:
a.T

/var/folders/d3/5yh4slqx3g375g3c6j08l6lm0000gn/T/ipykernel_41818/2533872927.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3618.)
  a.T


tensor([[[0.4947, 0.0767, 0.3362],
         [0.0729, 0.4706, 0.8592],
         [0.7213, 0.5978, 0.1451]],

        [[0.2577, 0.3047, 0.5042],
         [0.2032, 0.5555, 0.1586],
         [0.5609, 0.9008, 0.4788]],

        [[0.0593, 0.9098, 0.1604],
         [0.6913, 0.0136, 0.6206],
         [0.4829, 0.0293, 0.4833]]])

In [34]:
a = torch.arange(27).reshape(3,3,-1)
a

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [35]:
a.sum(axis=2, keepdims=True)

tensor([[[ 3],
         [12],
         [21]],

        [[30],
         [39],
         [48]],

        [[57],
         [66],
         [75]]])

In [36]:
a.cumsum(axis=1)

tensor([[[ 0,  1,  2],
         [ 3,  5,  7],
         [ 9, 12, 15]],

        [[ 9, 10, 11],
         [21, 23, 25],
         [36, 39, 42]],

        [[18, 19, 20],
         [39, 41, 43],
         [63, 66, 69]]])

### Matrix-Vector Products

In [37]:
a = torch.arange(9).reshape(3,-1)
a

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [38]:
x = torch.arange(3).reshape(1,3)
x

tensor([[0, 1, 2]])

In [39]:
x.T

tensor([[0],
        [1],
        [2]])

In [40]:
a@x.T

tensor([[ 5],
        [14],
        [23]])

In [42]:
a.shape, x.shape

(torch.Size([3, 3]), torch.Size([1, 3]))

## Automatic Differentiation

In [46]:
x = torch.arange(4, requires_grad=True, dtype=float)
x, x.grad

(tensor([0., 1., 2., 3.], dtype=torch.float64, requires_grad=True), None)

In [48]:
y = 2 * torch.dot(x,x)
y

tensor(28., dtype=torch.float64, grad_fn=<MulBackward0>)

In [49]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.], dtype=torch.float64)

In [50]:
x.grad.zero_()  # Reset the gradient
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.], dtype=torch.float64)

In [51]:
x.grad.zero_()
y = x * x
y.backward(gradient=torch.ones(len(y)))  # Faster: y.sum().backward()
x.grad

tensor([0., 2., 4., 6.], dtype=torch.float64)